---
spring:
  profiles: default  
server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
instance-name: ${spring.profiles}
 
---
spring:
  profiles: primary
server:
  port: 8006
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
instance-name: ${spring.profiles}
      
---
spring:
  profiles: secondary
server:
  port: 8007
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
instance-name: ${spring.profiles}      
---
spring:
  profiles: tertiary
server:
  port: 8008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
instance-name: ${spring.profiles}  

